// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 26.10.2025, 00:21:25
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/Emily/Desktop/Milena_Site/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Emily/Desktop/Milena_Site/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Emily/Desktop/Milena_Site/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Emily/Desktop/Milena_Site/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Emily/Desktop/Milena_Site/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Emily/Desktop/Milena_Site/plugins/**/*.{js,ts,mjs}","C:/Users/Emily/Desktop/Milena_Site/composables/**/*.{js,ts,mjs}","C:/Users/Emily/Desktop/Milena_Site/utils/**/*.{js,ts,mjs}","C:/Users/Emily/Desktop/Milena_Site/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Emily/Desktop/Milena_Site/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Emily/Desktop/Milena_Site/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;