
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'SectionsFooter': typeof import("../components/sections/footer/Footer.vue")['default']
    'SectionsHeader': typeof import("../components/sections/header/Header.vue")['default']
    'SharedBreadcrumbs': typeof import("../components/shared/breadcrumbs/Breadcrumbs.vue")['default']
    'SharedCardDetail': typeof import("../components/shared/card-detail/CardDetail.vue")['default']
    'SharedCardDetailTypes': typeof import("../components/shared/card-detail/types")['default']
    'SharedCardPreview': typeof import("../components/shared/card-preview/CardPreview.vue")['default']
    'SharedFilterGroup': typeof import("../components/shared/filter-group/FilterGroup.vue")['default']
    'Shared': typeof import("../components/shared/index")['default']
    'SharedNavigation': typeof import("../components/shared/navigation/Navigation.vue")['default']
    'SharedNavigationNavigationItem': typeof import("../components/shared/navigation/NavigationItem/NavigationItem.vue")['default']
    'SharedRequestModal': typeof import("../components/shared/request-modal/RequestModal.vue")['default']
    'SharedSocial': typeof import("../components/shared/social/Social.vue")['default']
    'SharedSocialSocialItem': typeof import("../components/shared/social/SocialItem/SocialItem.vue")['default']
    'UiBox': typeof import("../components/ui/box/Box.vue")['default']
    'UiButton': typeof import("../components/ui/button/Button.vue")['default']
    'UiFormError': typeof import("../components/ui/form-error/FormError.vue")['default']
    'Ui': typeof import("../components/ui/index")['default']
    'UiInput': typeof import("../components/ui/input/Input.vue")['default']
    'UiLoader': typeof import("../components/ui/loader/Loader.vue")['default']
    'UiModal': typeof import("../components/ui/modal/Modal.vue")['default']
    'UiMultiCheckbox': typeof import("../components/ui/multi-checkbox/MultiCheckbox.vue")['default']
    'UiPagination': typeof import("../components/ui/pagination/Pagination.vue")['default']
    'UiSelectDropdownItem': typeof import("../components/ui/select/DropdownItem/DropdownItem.vue")['default']
    'UiSelectDropdownList': typeof import("../components/ui/select/DropdownList/DropdownList.vue")['default']
    'UiSelectDropdownTitle': typeof import("../components/ui/select/DropdownTitle/DropdownTitle.vue")['default']
    'UiSelect': typeof import("../components/ui/select/Select.vue")['default']
    'UiSvgIcon': typeof import("../components/ui/svg-icon/SvgIcon.vue")['default']
    'UiTextarea': typeof import("../components/ui/textarea/Textarea.vue")['default']
    'UiTitle': typeof import("../components/ui/title/Title.vue")['default']
    'UiTypography': typeof import("../components/ui/typography/Typography.vue")['default']
    'ViewsHome': typeof import("../components/views/Home/Home.vue")['default']
    'ViewsHomeSectionsIntro': typeof import("../components/views/Home/sections/Intro/Intro.vue")['default']
    'ViewsHomeSectionsServicesServiceItem': typeof import("../components/views/Home/sections/Services/ServiceItem/ServiceItem.vue")['default']
    'ViewsHomeSectionsServicesServiceList': typeof import("../components/views/Home/sections/Services/ServiceList/ServiceList.vue")['default']
    'ViewsHomeSectionsServices': typeof import("../components/views/Home/sections/Services/Services.vue")['default']
    'ViewsHomeSectionsWorksWorkItem': typeof import("../components/views/Home/sections/Works/WorkItem/WorkItem.vue")['default']
    'ViewsHomeSectionsWorksWorkList': typeof import("../components/views/Home/sections/Works/WorkList/WorkList.vue")['default']
    'ViewsHomeSectionsWorks': typeof import("../components/views/Home/sections/Works/Works.vue")['default']
    'ViewsHomeSections': typeof import("../components/views/Home/sections/index")['default']
    'ViewsLogin': typeof import("../components/views/Login/Login.vue")['default']
    'ViewsLoginSectionsLoginForm': typeof import("../components/views/Login/sections/LoginForm/LoginForm.vue")['default']
    'ViewsLoginSections': typeof import("../components/views/Login/sections/index")['default']
    'ViewsRegister': typeof import("../components/views/Register/Register.vue")['default']
    'ViewsRegisterSectionsRegisterForm': typeof import("../components/views/Register/sections/RegisterForm/RegisterForm.vue")['default']
    'ViewsRegisterSectionsRegisterSuccess': typeof import("../components/views/Register/sections/RegisterSuccess/RegisterSuccess.vue")['default']
    'ViewsRegisterSections': typeof import("../components/views/Register/sections/index")['default']
    'ViewsWorkDetail': typeof import("../components/views/WorkDetail/WorkDetail.vue")['default']
    'ViewsWorks': typeof import("../components/views/Works/Works.vue")['default']
    'ViewsWorksSectionsFilterSectionCategoryFilter': typeof import("../components/views/Works/sections/FilterSection/CategoryFilter/CategoryFilter.vue")['default']
    'ViewsWorksSectionsFilterSection': typeof import("../components/views/Works/sections/FilterSection/FilterSection.vue")['default']
    'ViewsWorksSectionsFilterSectionMaterialFilter': typeof import("../components/views/Works/sections/FilterSection/MaterialFilter/MaterialFilter.vue")['default']
    'ViewsWorksSectionsFilterSectionMediumFilter': typeof import("../components/views/Works/sections/FilterSection/MediumFilter/MediumFilter.vue")['default']
    'ViewsWorksSectionsFilterSectionStyleFilter': typeof import("../components/views/Works/sections/FilterSection/StyleFilter/StyleFilter.vue")['default']
    'ViewsWorksSections': typeof import("../components/views/Works/sections/index")['default']
    'Views': typeof import("../components/views/index")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
    'NuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazySectionsFooter': typeof import("../components/sections/footer/Footer.vue")['default']
    'LazySectionsHeader': typeof import("../components/sections/header/Header.vue")['default']
    'LazySharedBreadcrumbs': typeof import("../components/shared/breadcrumbs/Breadcrumbs.vue")['default']
    'LazySharedCardDetail': typeof import("../components/shared/card-detail/CardDetail.vue")['default']
    'LazySharedCardDetailTypes': typeof import("../components/shared/card-detail/types")['default']
    'LazySharedCardPreview': typeof import("../components/shared/card-preview/CardPreview.vue")['default']
    'LazySharedFilterGroup': typeof import("../components/shared/filter-group/FilterGroup.vue")['default']
    'LazyShared': typeof import("../components/shared/index")['default']
    'LazySharedNavigation': typeof import("../components/shared/navigation/Navigation.vue")['default']
    'LazySharedNavigationNavigationItem': typeof import("../components/shared/navigation/NavigationItem/NavigationItem.vue")['default']
    'LazySharedRequestModal': typeof import("../components/shared/request-modal/RequestModal.vue")['default']
    'LazySharedSocial': typeof import("../components/shared/social/Social.vue")['default']
    'LazySharedSocialSocialItem': typeof import("../components/shared/social/SocialItem/SocialItem.vue")['default']
    'LazyUiBox': typeof import("../components/ui/box/Box.vue")['default']
    'LazyUiButton': typeof import("../components/ui/button/Button.vue")['default']
    'LazyUiFormError': typeof import("../components/ui/form-error/FormError.vue")['default']
    'LazyUi': typeof import("../components/ui/index")['default']
    'LazyUiInput': typeof import("../components/ui/input/Input.vue")['default']
    'LazyUiLoader': typeof import("../components/ui/loader/Loader.vue")['default']
    'LazyUiModal': typeof import("../components/ui/modal/Modal.vue")['default']
    'LazyUiMultiCheckbox': typeof import("../components/ui/multi-checkbox/MultiCheckbox.vue")['default']
    'LazyUiPagination': typeof import("../components/ui/pagination/Pagination.vue")['default']
    'LazyUiSelectDropdownItem': typeof import("../components/ui/select/DropdownItem/DropdownItem.vue")['default']
    'LazyUiSelectDropdownList': typeof import("../components/ui/select/DropdownList/DropdownList.vue")['default']
    'LazyUiSelectDropdownTitle': typeof import("../components/ui/select/DropdownTitle/DropdownTitle.vue")['default']
    'LazyUiSelect': typeof import("../components/ui/select/Select.vue")['default']
    'LazyUiSvgIcon': typeof import("../components/ui/svg-icon/SvgIcon.vue")['default']
    'LazyUiTextarea': typeof import("../components/ui/textarea/Textarea.vue")['default']
    'LazyUiTitle': typeof import("../components/ui/title/Title.vue")['default']
    'LazyUiTypography': typeof import("../components/ui/typography/Typography.vue")['default']
    'LazyViewsHome': typeof import("../components/views/Home/Home.vue")['default']
    'LazyViewsHomeSectionsIntro': typeof import("../components/views/Home/sections/Intro/Intro.vue")['default']
    'LazyViewsHomeSectionsServicesServiceItem': typeof import("../components/views/Home/sections/Services/ServiceItem/ServiceItem.vue")['default']
    'LazyViewsHomeSectionsServicesServiceList': typeof import("../components/views/Home/sections/Services/ServiceList/ServiceList.vue")['default']
    'LazyViewsHomeSectionsServices': typeof import("../components/views/Home/sections/Services/Services.vue")['default']
    'LazyViewsHomeSectionsWorksWorkItem': typeof import("../components/views/Home/sections/Works/WorkItem/WorkItem.vue")['default']
    'LazyViewsHomeSectionsWorksWorkList': typeof import("../components/views/Home/sections/Works/WorkList/WorkList.vue")['default']
    'LazyViewsHomeSectionsWorks': typeof import("../components/views/Home/sections/Works/Works.vue")['default']
    'LazyViewsHomeSections': typeof import("../components/views/Home/sections/index")['default']
    'LazyViewsLogin': typeof import("../components/views/Login/Login.vue")['default']
    'LazyViewsLoginSectionsLoginForm': typeof import("../components/views/Login/sections/LoginForm/LoginForm.vue")['default']
    'LazyViewsLoginSections': typeof import("../components/views/Login/sections/index")['default']
    'LazyViewsRegister': typeof import("../components/views/Register/Register.vue")['default']
    'LazyViewsRegisterSectionsRegisterForm': typeof import("../components/views/Register/sections/RegisterForm/RegisterForm.vue")['default']
    'LazyViewsRegisterSectionsRegisterSuccess': typeof import("../components/views/Register/sections/RegisterSuccess/RegisterSuccess.vue")['default']
    'LazyViewsRegisterSections': typeof import("../components/views/Register/sections/index")['default']
    'LazyViewsWorkDetail': typeof import("../components/views/WorkDetail/WorkDetail.vue")['default']
    'LazyViewsWorks': typeof import("../components/views/Works/Works.vue")['default']
    'LazyViewsWorksSectionsFilterSectionCategoryFilter': typeof import("../components/views/Works/sections/FilterSection/CategoryFilter/CategoryFilter.vue")['default']
    'LazyViewsWorksSectionsFilterSection': typeof import("../components/views/Works/sections/FilterSection/FilterSection.vue")['default']
    'LazyViewsWorksSectionsFilterSectionMaterialFilter': typeof import("../components/views/Works/sections/FilterSection/MaterialFilter/MaterialFilter.vue")['default']
    'LazyViewsWorksSectionsFilterSectionMediumFilter': typeof import("../components/views/Works/sections/FilterSection/MediumFilter/MediumFilter.vue")['default']
    'LazyViewsWorksSectionsFilterSectionStyleFilter': typeof import("../components/views/Works/sections/FilterSection/StyleFilter/StyleFilter.vue")['default']
    'LazyViewsWorksSections': typeof import("../components/views/Works/sections/index")['default']
    'LazyViews': typeof import("../components/views/index")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
    'LazyNuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const SectionsFooter: typeof import("../components/sections/footer/Footer.vue")['default']
export const SectionsHeader: typeof import("../components/sections/header/Header.vue")['default']
export const SharedBreadcrumbs: typeof import("../components/shared/breadcrumbs/Breadcrumbs.vue")['default']
export const SharedCardDetail: typeof import("../components/shared/card-detail/CardDetail.vue")['default']
export const SharedCardDetailTypes: typeof import("../components/shared/card-detail/types")['default']
export const SharedCardPreview: typeof import("../components/shared/card-preview/CardPreview.vue")['default']
export const SharedFilterGroup: typeof import("../components/shared/filter-group/FilterGroup.vue")['default']
export const Shared: typeof import("../components/shared/index")['default']
export const SharedNavigation: typeof import("../components/shared/navigation/Navigation.vue")['default']
export const SharedNavigationNavigationItem: typeof import("../components/shared/navigation/NavigationItem/NavigationItem.vue")['default']
export const SharedRequestModal: typeof import("../components/shared/request-modal/RequestModal.vue")['default']
export const SharedSocial: typeof import("../components/shared/social/Social.vue")['default']
export const SharedSocialSocialItem: typeof import("../components/shared/social/SocialItem/SocialItem.vue")['default']
export const UiBox: typeof import("../components/ui/box/Box.vue")['default']
export const UiButton: typeof import("../components/ui/button/Button.vue")['default']
export const UiFormError: typeof import("../components/ui/form-error/FormError.vue")['default']
export const Ui: typeof import("../components/ui/index")['default']
export const UiInput: typeof import("../components/ui/input/Input.vue")['default']
export const UiLoader: typeof import("../components/ui/loader/Loader.vue")['default']
export const UiModal: typeof import("../components/ui/modal/Modal.vue")['default']
export const UiMultiCheckbox: typeof import("../components/ui/multi-checkbox/MultiCheckbox.vue")['default']
export const UiPagination: typeof import("../components/ui/pagination/Pagination.vue")['default']
export const UiSelectDropdownItem: typeof import("../components/ui/select/DropdownItem/DropdownItem.vue")['default']
export const UiSelectDropdownList: typeof import("../components/ui/select/DropdownList/DropdownList.vue")['default']
export const UiSelectDropdownTitle: typeof import("../components/ui/select/DropdownTitle/DropdownTitle.vue")['default']
export const UiSelect: typeof import("../components/ui/select/Select.vue")['default']
export const UiSvgIcon: typeof import("../components/ui/svg-icon/SvgIcon.vue")['default']
export const UiTextarea: typeof import("../components/ui/textarea/Textarea.vue")['default']
export const UiTitle: typeof import("../components/ui/title/Title.vue")['default']
export const UiTypography: typeof import("../components/ui/typography/Typography.vue")['default']
export const ViewsHome: typeof import("../components/views/Home/Home.vue")['default']
export const ViewsHomeSectionsIntro: typeof import("../components/views/Home/sections/Intro/Intro.vue")['default']
export const ViewsHomeSectionsServicesServiceItem: typeof import("../components/views/Home/sections/Services/ServiceItem/ServiceItem.vue")['default']
export const ViewsHomeSectionsServicesServiceList: typeof import("../components/views/Home/sections/Services/ServiceList/ServiceList.vue")['default']
export const ViewsHomeSectionsServices: typeof import("../components/views/Home/sections/Services/Services.vue")['default']
export const ViewsHomeSectionsWorksWorkItem: typeof import("../components/views/Home/sections/Works/WorkItem/WorkItem.vue")['default']
export const ViewsHomeSectionsWorksWorkList: typeof import("../components/views/Home/sections/Works/WorkList/WorkList.vue")['default']
export const ViewsHomeSectionsWorks: typeof import("../components/views/Home/sections/Works/Works.vue")['default']
export const ViewsHomeSections: typeof import("../components/views/Home/sections/index")['default']
export const ViewsLogin: typeof import("../components/views/Login/Login.vue")['default']
export const ViewsLoginSectionsLoginForm: typeof import("../components/views/Login/sections/LoginForm/LoginForm.vue")['default']
export const ViewsLoginSections: typeof import("../components/views/Login/sections/index")['default']
export const ViewsRegister: typeof import("../components/views/Register/Register.vue")['default']
export const ViewsRegisterSectionsRegisterForm: typeof import("../components/views/Register/sections/RegisterForm/RegisterForm.vue")['default']
export const ViewsRegisterSectionsRegisterSuccess: typeof import("../components/views/Register/sections/RegisterSuccess/RegisterSuccess.vue")['default']
export const ViewsRegisterSections: typeof import("../components/views/Register/sections/index")['default']
export const ViewsWorkDetail: typeof import("../components/views/WorkDetail/WorkDetail.vue")['default']
export const ViewsWorks: typeof import("../components/views/Works/Works.vue")['default']
export const ViewsWorksSectionsFilterSectionCategoryFilter: typeof import("../components/views/Works/sections/FilterSection/CategoryFilter/CategoryFilter.vue")['default']
export const ViewsWorksSectionsFilterSection: typeof import("../components/views/Works/sections/FilterSection/FilterSection.vue")['default']
export const ViewsWorksSectionsFilterSectionMaterialFilter: typeof import("../components/views/Works/sections/FilterSection/MaterialFilter/MaterialFilter.vue")['default']
export const ViewsWorksSectionsFilterSectionMediumFilter: typeof import("../components/views/Works/sections/FilterSection/MediumFilter/MediumFilter.vue")['default']
export const ViewsWorksSectionsFilterSectionStyleFilter: typeof import("../components/views/Works/sections/FilterSection/StyleFilter/StyleFilter.vue")['default']
export const ViewsWorksSections: typeof import("../components/views/Works/sections/index")['default']
export const Views: typeof import("../components/views/index")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
export const NuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazySectionsFooter: typeof import("../components/sections/footer/Footer.vue")['default']
export const LazySectionsHeader: typeof import("../components/sections/header/Header.vue")['default']
export const LazySharedBreadcrumbs: typeof import("../components/shared/breadcrumbs/Breadcrumbs.vue")['default']
export const LazySharedCardDetail: typeof import("../components/shared/card-detail/CardDetail.vue")['default']
export const LazySharedCardDetailTypes: typeof import("../components/shared/card-detail/types")['default']
export const LazySharedCardPreview: typeof import("../components/shared/card-preview/CardPreview.vue")['default']
export const LazySharedFilterGroup: typeof import("../components/shared/filter-group/FilterGroup.vue")['default']
export const LazyShared: typeof import("../components/shared/index")['default']
export const LazySharedNavigation: typeof import("../components/shared/navigation/Navigation.vue")['default']
export const LazySharedNavigationNavigationItem: typeof import("../components/shared/navigation/NavigationItem/NavigationItem.vue")['default']
export const LazySharedRequestModal: typeof import("../components/shared/request-modal/RequestModal.vue")['default']
export const LazySharedSocial: typeof import("../components/shared/social/Social.vue")['default']
export const LazySharedSocialSocialItem: typeof import("../components/shared/social/SocialItem/SocialItem.vue")['default']
export const LazyUiBox: typeof import("../components/ui/box/Box.vue")['default']
export const LazyUiButton: typeof import("../components/ui/button/Button.vue")['default']
export const LazyUiFormError: typeof import("../components/ui/form-error/FormError.vue")['default']
export const LazyUi: typeof import("../components/ui/index")['default']
export const LazyUiInput: typeof import("../components/ui/input/Input.vue")['default']
export const LazyUiLoader: typeof import("../components/ui/loader/Loader.vue")['default']
export const LazyUiModal: typeof import("../components/ui/modal/Modal.vue")['default']
export const LazyUiMultiCheckbox: typeof import("../components/ui/multi-checkbox/MultiCheckbox.vue")['default']
export const LazyUiPagination: typeof import("../components/ui/pagination/Pagination.vue")['default']
export const LazyUiSelectDropdownItem: typeof import("../components/ui/select/DropdownItem/DropdownItem.vue")['default']
export const LazyUiSelectDropdownList: typeof import("../components/ui/select/DropdownList/DropdownList.vue")['default']
export const LazyUiSelectDropdownTitle: typeof import("../components/ui/select/DropdownTitle/DropdownTitle.vue")['default']
export const LazyUiSelect: typeof import("../components/ui/select/Select.vue")['default']
export const LazyUiSvgIcon: typeof import("../components/ui/svg-icon/SvgIcon.vue")['default']
export const LazyUiTextarea: typeof import("../components/ui/textarea/Textarea.vue")['default']
export const LazyUiTitle: typeof import("../components/ui/title/Title.vue")['default']
export const LazyUiTypography: typeof import("../components/ui/typography/Typography.vue")['default']
export const LazyViewsHome: typeof import("../components/views/Home/Home.vue")['default']
export const LazyViewsHomeSectionsIntro: typeof import("../components/views/Home/sections/Intro/Intro.vue")['default']
export const LazyViewsHomeSectionsServicesServiceItem: typeof import("../components/views/Home/sections/Services/ServiceItem/ServiceItem.vue")['default']
export const LazyViewsHomeSectionsServicesServiceList: typeof import("../components/views/Home/sections/Services/ServiceList/ServiceList.vue")['default']
export const LazyViewsHomeSectionsServices: typeof import("../components/views/Home/sections/Services/Services.vue")['default']
export const LazyViewsHomeSectionsWorksWorkItem: typeof import("../components/views/Home/sections/Works/WorkItem/WorkItem.vue")['default']
export const LazyViewsHomeSectionsWorksWorkList: typeof import("../components/views/Home/sections/Works/WorkList/WorkList.vue")['default']
export const LazyViewsHomeSectionsWorks: typeof import("../components/views/Home/sections/Works/Works.vue")['default']
export const LazyViewsHomeSections: typeof import("../components/views/Home/sections/index")['default']
export const LazyViewsLogin: typeof import("../components/views/Login/Login.vue")['default']
export const LazyViewsLoginSectionsLoginForm: typeof import("../components/views/Login/sections/LoginForm/LoginForm.vue")['default']
export const LazyViewsLoginSections: typeof import("../components/views/Login/sections/index")['default']
export const LazyViewsRegister: typeof import("../components/views/Register/Register.vue")['default']
export const LazyViewsRegisterSectionsRegisterForm: typeof import("../components/views/Register/sections/RegisterForm/RegisterForm.vue")['default']
export const LazyViewsRegisterSectionsRegisterSuccess: typeof import("../components/views/Register/sections/RegisterSuccess/RegisterSuccess.vue")['default']
export const LazyViewsRegisterSections: typeof import("../components/views/Register/sections/index")['default']
export const LazyViewsWorkDetail: typeof import("../components/views/WorkDetail/WorkDetail.vue")['default']
export const LazyViewsWorks: typeof import("../components/views/Works/Works.vue")['default']
export const LazyViewsWorksSectionsFilterSectionCategoryFilter: typeof import("../components/views/Works/sections/FilterSection/CategoryFilter/CategoryFilter.vue")['default']
export const LazyViewsWorksSectionsFilterSection: typeof import("../components/views/Works/sections/FilterSection/FilterSection.vue")['default']
export const LazyViewsWorksSectionsFilterSectionMaterialFilter: typeof import("../components/views/Works/sections/FilterSection/MaterialFilter/MaterialFilter.vue")['default']
export const LazyViewsWorksSectionsFilterSectionMediumFilter: typeof import("../components/views/Works/sections/FilterSection/MediumFilter/MediumFilter.vue")['default']
export const LazyViewsWorksSectionsFilterSectionStyleFilter: typeof import("../components/views/Works/sections/FilterSection/StyleFilter/StyleFilter.vue")['default']
export const LazyViewsWorksSections: typeof import("../components/views/Works/sections/index")['default']
export const LazyViews: typeof import("../components/views/index")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
export const LazyNuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
